apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  email: YWRtaW5AcGdhZG1pbi5vcmc=   # admin@pgadmin.org (base64)
  password: cGFzc3dvcmQ=           # password (base64)
