name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name demo-eks-cluster

      - name: Deploy PostgreSQL
        run: kubectl apply -f k8s/postgresql/

      - name: Deploy pgAdmin
        run: kubectl apply -f k8s/pgadmin/

      - name: Deploy Grafana
        run: kubectl apply -f k8s/grafana/

      - name: Deploy Prometheus
        run: kubectl apply -f k8s/monitoring/

      - name: Deploy Monitoring Stack
        run: |
          kubectl apply -f k8s/monitoring/prometheus-configmap.yaml
          kubectl apply -f k8s/monitoring/prometheus-deployment.yaml
          kubectl apply -f k8s/monitoring/prometheus-service.yaml
          kubectl apply -f k8s/monitoring/postgres-exporter.yaml
          kubectl apply -f k8s/monitoring/grafana-datasources.yaml
          kubectl apply -f k8s/monitoring/grafana-dashboard-provider.yaml


